package com.hw.messagemodule.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hw.messagemodule.data.bean.ChatBean;
import com.hw.messagemodule.data.bean.ChatBeanLastMessage;

import com.hw.messagemodule.db.ChatBeanDao;
import com.hw.messagemodule.db.ChatBeanLastMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatBeanDaoConfig;
    private final DaoConfig chatBeanLastMessageDaoConfig;

    private final ChatBeanDao chatBeanDao;
    private final ChatBeanLastMessageDao chatBeanLastMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatBeanDaoConfig = daoConfigMap.get(ChatBeanDao.class).clone();
        chatBeanDaoConfig.initIdentityScope(type);

        chatBeanLastMessageDaoConfig = daoConfigMap.get(ChatBeanLastMessageDao.class).clone();
        chatBeanLastMessageDaoConfig.initIdentityScope(type);

        chatBeanDao = new ChatBeanDao(chatBeanDaoConfig, this);
        chatBeanLastMessageDao = new ChatBeanLastMessageDao(chatBeanLastMessageDaoConfig, this);

        registerDao(ChatBean.class, chatBeanDao);
        registerDao(ChatBeanLastMessage.class, chatBeanLastMessageDao);
    }
    
    public void clear() {
        chatBeanDaoConfig.clearIdentityScope();
        chatBeanLastMessageDaoConfig.clearIdentityScope();
    }

    public ChatBeanDao getChatBeanDao() {
        return chatBeanDao;
    }

    public ChatBeanLastMessageDao getChatBeanLastMessageDao() {
        return chatBeanLastMessageDao;
    }

}
